/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as AuthenticatedVitalsRouteImport } from './routes/_authenticated/vitals'
import { Route as AuthenticatedSymptomCheckerRouteImport } from './routes/_authenticated/symptom-checker'
import { Route as AuthenticatedScansRouteImport } from './routes/_authenticated/scans'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedMedicalAnalysisRouteImport } from './routes/_authenticated/medical-analysis'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultRouteImport } from './routes/_authenticated/consult'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVitalsRoute = AuthenticatedVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSymptomCheckerRoute =
  AuthenticatedSymptomCheckerRouteImport.update({
    id: '/symptom-checker',
    path: '/symptom-checker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScansRoute = AuthenticatedScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicalAnalysisRoute =
  AuthenticatedMedicalAnalysisRouteImport.update({
    id: '/medical-analysis',
    path: '/medical-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsultRoute = AuthenticatedConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/consult': typeof AuthenticatedConsultRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/medical-analysis': typeof AuthenticatedMedicalAnalysisRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/scans': typeof AuthenticatedScansRoute
  '/symptom-checker': typeof AuthenticatedSymptomCheckerRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/consult': typeof AuthenticatedConsultRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/medical-analysis': typeof AuthenticatedMedicalAnalysisRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/scans': typeof AuthenticatedScansRoute
  '/symptom-checker': typeof AuthenticatedSymptomCheckerRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/consult': typeof AuthenticatedConsultRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/medical-analysis': typeof AuthenticatedMedicalAnalysisRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/scans': typeof AuthenticatedScansRoute
  '/_authenticated/symptom-checker': typeof AuthenticatedSymptomCheckerRoute
  '/_authenticated/vitals': typeof AuthenticatedVitalsRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/appointments'
    | '/chatbot'
    | '/consult'
    | '/dashboard'
    | '/emergency'
    | '/history'
    | '/medical-analysis'
    | '/nearby'
    | '/scans'
    | '/symptom-checker'
    | '/vitals'
    | '/api/chat-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/appointments'
    | '/chatbot'
    | '/consult'
    | '/dashboard'
    | '/emergency'
    | '/history'
    | '/medical-analysis'
    | '/nearby'
    | '/scans'
    | '/symptom-checker'
    | '/vitals'
    | '/api/chat-stream'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/appointments'
    | '/_authenticated/chatbot'
    | '/_authenticated/consult'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergency'
    | '/_authenticated/history'
    | '/_authenticated/medical-analysis'
    | '/_authenticated/nearby'
    | '/_authenticated/scans'
    | '/_authenticated/symptom-checker'
    | '/_authenticated/vitals'
    | '/api/chat-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vitals': {
      id: '/_authenticated/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthenticatedVitalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/symptom-checker': {
      id: '/_authenticated/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof AuthenticatedSymptomCheckerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scans': {
      id: '/_authenticated/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedScansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medical-analysis': {
      id: '/_authenticated/medical-analysis'
      path: '/medical-analysis'
      fullPath: '/medical-analysis'
      preLoaderRoute: typeof AuthenticatedMedicalAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consult': {
      id: '/_authenticated/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof AuthenticatedConsultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedConsultRoute: typeof AuthenticatedConsultRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMedicalAnalysisRoute: typeof AuthenticatedMedicalAnalysisRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedScansRoute: typeof AuthenticatedScansRoute
  AuthenticatedSymptomCheckerRoute: typeof AuthenticatedSymptomCheckerRoute
  AuthenticatedVitalsRoute: typeof AuthenticatedVitalsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedConsultRoute: AuthenticatedConsultRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMedicalAnalysisRoute: AuthenticatedMedicalAnalysisRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedScansRoute: AuthenticatedScansRoute,
  AuthenticatedSymptomCheckerRoute: AuthenticatedSymptomCheckerRoute,
  AuthenticatedVitalsRoute: AuthenticatedVitalsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
